---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 13.8.5
  install_strategy: always
  channel: stable

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: centos-6
  - name: debian-8
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[nfs::default]
  - name: server
    run_list:
    - recipe[nfs::server]
    - recipe[nfs_test::issue46]
    attributes:
